from __future__ import annotations

from typing import Final

from src.schemas import IntentName

ROUTER_PROTOTYPES: Final[dict[IntentName, tuple[str, ...]]] = {
    "summarization": (
        "summarize this",
        "summarize this text",
        "give me a summary",
        "tl dr",
        "sum this up",
        "brief summary",
        "condense this",
        "make it shorter",
        "make this shorter",
        "shorten this article",
        "shorten this text",
        "make this more concise",
        "abstract this text",
        "can you summarize",
        "resuma",
        "resuma este texto",
        "resuma isso",
        "resumo disso",
        "me da um resumo",
        "pode resumir",
        "faca um resumo",
    ),
    "question_answering": (
        "what is the capital",
        "what is machine learning",
        "what is docker",
        "what is a neural network",
        "who invented",
        "how does this work",
        "why does",
        "when did this happen",
        "where is located",
        "explain to me",
        "tell me about",
        "could you explain",
        "help me understand",
        "qual e a capital",
        "como funciona",
        "o que e",
        "quem e",
        "quem foi",
        "me fale sobre",
        "me conta sobre",
        "me explique",
        "onde fica",
        "por que",
        "quando foi",
        "me diga sobre",
        "i want to know about",
        "can you tell me",
    ),
    "function_calling": (
        "calculate",
        "compute this",
        "what is 3 plus 5",
        "run the tool",
        "evaluate this expression",
        "math problem",
        "add these numbers",
        "multiply",
        "divide by",
        "what is 2 times 3",
        "calcule",
        "resultado de",
        "search for",
        "search the web for",
        "look up",
        "fetch the url",
        "fetch this page",
        "look up on wikipedia",
        "find information about",
        "latest news about",
        "recent news on",
        "current news about",
        "ultimas noticias sobre",
        "noticias recentes",
    ),
    "classification": (
        "classify this text",
        "determine the category",
        "label this text",
        "detect the sentiment",
        "classify this sentiment",
        "is this positive or negative",
        "what type of text is this",
        "categorize this",
        "assign a label",
        "find the category",
        "determine intent of this text",
    ),
    "image_understanding": (
        "what is in this image",
        "describe the picture",
        "analyze this photo",
        "what do you see",
        "look at this image",
        "read this screenshot",
        "what does the image show",
    ),
    "general": (
        "hello",
        "hi there",
        "hey",
        "good morning",
        "good evening",
        "how are you",
        "what can you do",
        "thanks",
        "thank you",
        "oi",
        "ola",
    ),
}
